/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c7c7c3",
        "on-secondary-fixed-variant": "#663e00",
        surface: "#fff8f3",
        error: "#ba1a1a",
        "surface-container": "#f5ece5",
        "surface-container-high": "#efe7e0",
        "primary-fixed-dim": "#89d6ae",
        "surface-variant": "#e9e1da",
        "on-surface-variant": "#3f4943",
        "primary-container": "#2f7d5b",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb963",
        outline: "#6f7a72",
        "on-error": "#ffffff",
        "outline-variant": "#bec9c1",
        "on-tertiary-fixed-variant": "#464744",
        "on-secondary-container": "#714500",
        "on-background": "#1e1b17",
        "secondary-container": "#feb14f",
        "on-tertiary-container": "#f5f4f1",
        "on-primary-container": "#d1ffe3",
        "tertiary-container": "#6f706d",
        primary: "#0b6444",
        "secondary-fixed": "#ffddb9",
        "surface-container-low": "#fbf2eb",
        "tertiary-fixed": "#e3e2df",
        "surface-dim": "#e1d9d2",
        "on-primary-fixed-variant": "#005236",
        "on-surface": "#1e1b17",
        "on-primary-fixed": "#002113",
        "primary-fixed": "#a4f3c9",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#2b1700",
        "on-tertiary-fixed": "#1b1c1a",
        "inverse-primary": "#89d6ae",
        "surface-bright": "#fff8f3",
        secondary: "#865300",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f8efe8",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-tint": "#186b4b",
        background: "#fff8f3",
        tertiary: "#575855",
        "surface-container-highest": "#e9e1da",
        "inverse-surface": "#34302b",
        // structural line color from design md
        line: "#E8E6DF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-desktop": "40px",
        "stack-lg": "32px",
        gutter: "16px",
        "container-padding-mobile": "20px",
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
      },
      fontFamily: {
        // Head texts → Founders Grotesk
        "display-lg": ["Founders Grotesk", "sans-serif"],
        "headline-lg": ["Founders Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Founders Grotesk", "sans-serif"],
        "headline-md": ["Founders Grotesk", "sans-serif"],
        // Sub texts → Outfit
        "body-md": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "label-md": ["Outfit", "sans-serif"],
        "label-sm": ["Outfit", "sans-serif"],
        sans: ["Outfit", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
      },
      boxShadow: {
        editorial:
          "0 1px 2px rgba(22, 13, 15, 0.04), 0 12px 28px rgba(22, 13, 15, 0.06)",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "pulse-border": {
          "0%, 100%": { borderColor: "rgba(11, 100, 68, 0.3)" },
          "50%": { borderColor: "rgba(11, 100, 68, 0.8)" },
        },
      },
      animation: {
        shimmer: "shimmer 1.5s infinite",
        "pulse-border": "pulse-border 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
